# Generated by Django 5.0.2 on 2024-02-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alert_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
