# Generated by Django 5.0.2 on 2024-02-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0002_customer_alert_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alert_message',
            field=models.CharField(default='Account created! Make an order today!', max_length=255),
        ),
    ]
