# Generated by Django 5.0.2 on 2024-02-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0003_alter_customer_alert_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='code',
            new_name='phone_number',
        ),
    ]
